"""Shared branded-PDF theme for every generated document (Issue #98).

One module defines the **BK ClinicQ** document identity so every generator — lease
agreements, payment receipts, owner statements, tenant ledgers, inspection reports, the
occupancy/income/maintenance reports and the e-signature certificate — renders the same
recognisable document instead of hand-rolling flowables. It supplies:

* a **header** on every page: the company logo (a self-contained vector wordmark) and name,
  the document title, and — right-aligned — the reference and date;
* a **footer** on every page: a hairline rule, a legal / contact line, ``Page X of Y``, and
  the **electronic stamp** line (``Generated by BK ClinicQ · <date> · Ref <id>``);
* an **approval stamp** — a bordered ``APPROVED`` / ``EXECUTED`` / ``PAID`` mark drawn on the
  first page of documents that carry one (:class:`StampKind`);
* a shared **type scale** (:func:`styles`) and a **money table** (:func:`money_table`) for the
  aligned, right-justified amounts of the invoice / receipt / statement money documents.

Design decisions worth stating:

* **No external asset fetch.** The logo is drawn from ReportLab primitives (a rounded
  brand-colour tile with the ``BK`` monogram, then the company name), so the bytes are
  self-contained — nothing is read from disk or the network at render time. This keeps output
  deterministic and the golden-style tests stable.
* **Deterministic.** Given the same content and :class:`DocumentMeta` the layout is a pure
  function of its inputs; callers that need byte-stable output simply pass a fixed date.
* **``Page X of Y``.** The total page count is only known once layout finishes, so
  :class:`_BrandedCanvas` buffers each page and stamps the header, footer and stamp on a second
  pass when the total is known — the standard two-pass ReportLab idiom.
"""

from dataclasses import dataclass
from datetime import date
from decimal import Decimal
from enum import StrEnum
from io import BytesIO

from reportlab.lib import colors
from reportlab.lib.enums import TA_LEFT, TA_RIGHT
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import ParagraphStyle
from reportlab.lib.units import mm
from reportlab.pdfgen import canvas
from reportlab.platypus import (
    Flowable,
    Paragraph,
    SimpleDocTemplate,
    Spacer,
    Table,
    TableStyle,
)

# --------------------------------------------------------------------------------------
# Brand — one palette and one identity, mirrored from the app's emerald accent.
# --------------------------------------------------------------------------------------

#: Company name shown in the header and stamp. Mirrors ``Settings.app_name``; kept as a
#: constant here so a renderer stays a pure function with no settings dependency.
COMPANY_NAME = "BK ClinicQ"

#: The single legal / contact line printed in every footer.
LEGAL_LINE = (
    "BK ClinicQ · Cape Town, South Africa · "
    "accounts@bkproperties.co.za · This is a system-generated document."
)

_BRAND_PRIMARY = colors.HexColor("#047857")  # emerald — the BK accent
_BRAND_INK = colors.HexColor("#111827")  # near-black body text
_BRAND_MUTED = colors.HexColor("#6B7280")  # secondary / footer text
_BRAND_RULE = colors.HexColor("#D1D5DB")  # hairline rules
_BRAND_ZEBRA = colors.HexColor("#F3F4F6")  # alternate table-row fill

# Page geometry (A4). The top and bottom margins leave room for the header/footer the
# canvas draws outside the flowable frame.
_PAGE_SIZE = A4
_MARGIN_X = 18 * mm
_MARGIN_TOP = 34 * mm
_MARGIN_BOTTOM = 24 * mm


class StampKind(StrEnum):
    """The electronic stamp a document carries, drawn as a bordered mark on the first page.

    ``GENERATED`` is the implicit default (no boxed stamp, only the footer stamp line); the
    others mark a document whose state warrants a visible seal.
    """

    GENERATED = "generated"
    APPROVED = "approved"
    EXECUTED = "executed"
    PAID = "paid"


@dataclass(frozen=True, slots=True)
class DocumentMeta:
    """The header/footer/stamp context for one rendered document.

    Everything the theme needs that is *not* body content: the document title (header, left),
    an optional reference and date (header, right; also the footer stamp line), and the optional
    approval :class:`StampKind`.
    """

    title: str
    reference: str | None = None
    document_date: date | None = None
    stamp: StampKind = StampKind.GENERATED


def _format_minor(amount_minor: int) -> str:
    """Format an integer minor-unit amount as major units to two decimals (e.g. ``7500.00``).

    Uses :class:`~decimal.Decimal` so the money value is exact — never a float — matching how
    amounts are stored and displayed everywhere else in the domain. Signed, so a credit reads
    naturally.
    """
    return f"{Decimal(amount_minor) / Decimal(100):.2f}"


# --------------------------------------------------------------------------------------
# Type scale — one set of paragraph styles every generator draws its text with.
# --------------------------------------------------------------------------------------


def styles() -> dict[str, ParagraphStyle]:
    """Return the shared paragraph styles (title, heading, body, small, footer).

    A single type scale so no generator hand-rolls its own fonts or sizes. ``heading`` is used
    for the ALL-CAPS section labels the line-based bodies already emit; ``body`` for ordinary
    lines; ``small`` for fine print.
    """
    base = ParagraphStyle(
        "BkBody",
        fontName="Helvetica",
        fontSize=10.5,
        leading=15,
        textColor=_BRAND_INK,
        alignment=TA_LEFT,
    )
    return {
        "title": ParagraphStyle(
            "BkTitle", parent=base, fontName="Helvetica-Bold", fontSize=15, leading=19
        ),
        "heading": ParagraphStyle(
            "BkHeading",
            parent=base,
            fontName="Helvetica-Bold",
            fontSize=11,
            leading=15,
            textColor=_BRAND_PRIMARY,
            spaceBefore=6,
        ),
        "body": base,
        "small": ParagraphStyle(
            "BkSmall", parent=base, fontSize=8.5, leading=12, textColor=_BRAND_MUTED
        ),
        "amount": ParagraphStyle(
            "BkAmount", parent=base, alignment=TA_RIGHT, fontName="Helvetica"
        ),
    }


# --------------------------------------------------------------------------------------
# Money table — aligned, right-justified amounts with a ruled total (money documents).
# --------------------------------------------------------------------------------------


@dataclass(frozen=True, slots=True)
class MoneyLine:
    """One row of a money table: a label, an exact minor-unit amount, and optional detail.

    ``detail`` is a secondary column (a due date, a charge type, a period) shown between the
    label and the right-aligned amount.
    """

    label: str
    amount_minor: int
    detail: str = ""


def money_table(
    lines: list[MoneyLine],
    *,
    currency: str,
    total_label: str | None = None,
    total_minor: int | None = None,
) -> Table:
    """Lay money ``lines`` out as an aligned table with right-justified amounts (Issue #98).

    The amount column is right-aligned and carries the currency, so columns of money read down
    cleanly; every amount is formatted from exact integer minor units (never a float). When
    ``total_label`` / ``total_minor`` are given a bold, rule-topped total row is appended.

    Args:
        lines: The body rows (label, optional detail, minor-unit amount).
        currency: The ISO currency code shown against each amount.
        total_label: Label for the optional total row.
        total_minor: Minor-unit total for the optional total row.

    Returns:
        A styled ReportLab :class:`~reportlab.platypus.Table`, ready to place in a story.
    """
    header = ["Description", "", f"Amount ({currency})"]
    data: list[list[str]] = [header]
    for line in lines:
        data.append([line.label, line.detail, _format_minor(line.amount_minor)])

    # A total row, when requested, follows the body; the zebra fill covers only the body rows.
    total_row: int | None = None
    if total_label is not None and total_minor is not None:
        data.append([total_label, "", _format_minor(total_minor)])
        total_row = len(data) - 1

    style = TableStyle(
        [
            ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
            ("FONTSIZE", (0, 0), (-1, -1), 9.5),
            ("TEXTCOLOR", (0, 0), (-1, 0), _BRAND_PRIMARY),
            ("LINEBELOW", (0, 0), (-1, 0), 0.75, _BRAND_PRIMARY),
            ("ALIGN", (2, 0), (2, -1), "RIGHT"),  # amounts, right-aligned
            ("ALIGN", (1, 0), (1, -1), "LEFT"),
            ("TEXTCOLOR", (0, 1), (-1, -1), _BRAND_INK),
            ("TOPPADDING", (0, 0), (-1, -1), 4),
            ("BOTTOMPADDING", (0, 0), (-1, -1), 4),
            ("ROWBACKGROUNDS", (0, 1), (-1, len(lines)), [colors.white, _BRAND_ZEBRA]),
        ]
    )
    if total_row is not None:
        # Bold, rule-topped total row — added via ``TableStyle.add`` to keep the base literal flat.
        style.add("FONTNAME", (0, total_row), (-1, total_row), "Helvetica-Bold")
        style.add("LINEABOVE", (0, total_row), (-1, total_row), 0.75, _BRAND_INK)
        style.add("TEXTCOLOR", (0, total_row), (-1, total_row), _BRAND_INK)

    table = Table(data, colWidths=[80 * mm, 55 * mm, 39 * mm], hAlign="LEFT")
    table.setStyle(style)
    return table


# --------------------------------------------------------------------------------------
# The branded canvas — draws the header, footer and stamp once the page total is known.
# --------------------------------------------------------------------------------------


def _draw_logo(pdf: canvas.Canvas, x: float, y_top: float) -> None:
    """Draw the vector BK wordmark (tile + monogram + company name) with its top at ``y_top``.

    Entirely primitive-drawn so no image asset is embedded or fetched.
    """
    tile = 9 * mm
    top = y_top - tile
    pdf.setFillColor(_BRAND_PRIMARY)
    pdf.roundRect(x, top, tile, tile, 1.6 * mm, stroke=0, fill=1)
    pdf.setFillColor(colors.white)
    pdf.setFont("Helvetica-Bold", 11)
    pdf.drawCentredString(x + tile / 2, top + tile / 2 - 4, "BK")
    pdf.setFillColor(_BRAND_INK)
    pdf.setFont("Helvetica-Bold", 13)
    pdf.drawString(x + tile + 3 * mm, top + tile / 2 - 4, COMPANY_NAME)


def _draw_stamp(
    pdf: canvas.Canvas, kind: StampKind, x_right: float, y_top: float
) -> None:
    """Draw a bordered approval stamp (``APPROVED`` / ``EXECUTED`` / ``PAID``) top-right.

    Skipped for :attr:`StampKind.GENERATED`, whose only mark is the footer stamp line.
    """
    if kind is StampKind.GENERATED:
        return
    label = kind.value.upper()
    width, height = 34 * mm, 12 * mm
    x = x_right - width
    y = y_top - height
    pdf.saveState()
    pdf.setStrokeColor(_BRAND_PRIMARY)
    pdf.setLineWidth(1.4)
    pdf.roundRect(x, y, width, height, 1.5 * mm, stroke=1, fill=0)
    pdf.setFillColor(_BRAND_PRIMARY)
    pdf.setFont("Helvetica-Bold", 13)
    pdf.drawCentredString(x + width / 2, y + height / 2 - 4.5, label)
    pdf.restoreState()


def _draw_furniture(
    pdf: canvas.Canvas, meta: DocumentMeta, *, page: int, total: int
) -> None:
    """Draw the header, footer and (first-page) stamp for one page.

    Called once per page on the second pass, when ``total`` is known, so the footer can print
    ``Page X of Y``. The header carries the logo, title and right-aligned reference/date; the
    footer carries the legal line, the page number and the electronic stamp line.
    """
    width, height = _PAGE_SIZE
    right = width - _MARGIN_X

    # --- Header -----------------------------------------------------------------------
    header_top = height - 14 * mm
    _draw_logo(pdf, _MARGIN_X, header_top)

    pdf.setFillColor(_BRAND_INK)
    pdf.setFont("Helvetica-Bold", 12)
    pdf.drawString(_MARGIN_X, header_top - 12 * mm, meta.title)

    pdf.setFillColor(_BRAND_MUTED)
    pdf.setFont("Helvetica", 8.5)
    if meta.reference:
        pdf.drawRightString(right, header_top - 3, f"Ref: {meta.reference}")
    if meta.document_date is not None:
        pdf.drawRightString(
            right, header_top - 5 - 10, f"Date: {meta.document_date.isoformat()}"
        )

    # Hairline under the header, separating furniture from body.
    rule_y = height - _MARGIN_TOP + 6 * mm
    pdf.setStrokeColor(_BRAND_RULE)
    pdf.setLineWidth(0.5)
    pdf.line(_MARGIN_X, rule_y, right, rule_y)

    # Approval stamp — first page only, aligned to the header band.
    if page == 1:
        _draw_stamp(pdf, meta.stamp, right, header_top - 11 * mm)

    # --- Footer -----------------------------------------------------------------------
    footer_y = _MARGIN_BOTTOM - 8 * mm
    pdf.setStrokeColor(_BRAND_RULE)
    pdf.setLineWidth(0.5)
    pdf.line(_MARGIN_X, footer_y + 9, right, footer_y + 9)

    pdf.setFillColor(_BRAND_MUTED)
    pdf.setFont("Helvetica", 7.5)
    pdf.drawString(_MARGIN_X, footer_y, LEGAL_LINE)
    pdf.drawRightString(right, footer_y, f"Page {page} of {total}")

    # Electronic stamp line — provenance on every page.
    stamp_bits = [f"Generated by {COMPANY_NAME}"]
    if meta.document_date is not None:
        stamp_bits.append(meta.document_date.isoformat())
    if meta.reference:
        stamp_bits.append(f"Ref {meta.reference}")
    pdf.setFont("Helvetica-Oblique", 7)
    pdf.drawString(_MARGIN_X, footer_y - 9, " · ".join(stamp_bits))


class _BrandedCanvas(canvas.Canvas):
    """A two-pass canvas that stamps the branded furniture once the page total is known.

    During ``build`` each page is buffered rather than finalised; at ``save`` the pages are
    replayed with the total in hand so every page can print ``Page X of Y`` and the header /
    footer / stamp. The :attr:`meta` is injected by :func:`_canvas_factory`.
    """

    meta: DocumentMeta

    def __init__(self, *args, **kwargs) -> None:
        """Initialise the canvas with an empty buffer of saved page states."""
        super().__init__(*args, **kwargs)
        self._saved_page_states: list[dict] = []

    def showPage(self) -> None:  # noqa: N802 — ReportLab API name
        """Buffer the current page's state instead of finalising it (first pass)."""
        self._saved_page_states.append(dict(self.__dict__))
        self._startPage()  # type: ignore[attr-defined]  # ReportLab internal, untyped in stubs

    def save(self) -> None:
        """Replay every buffered page, drawing the furniture with the total known (second pass)."""
        total = len(self._saved_page_states)
        for index, state in enumerate(self._saved_page_states, start=1):
            self.__dict__.update(state)
            _draw_furniture(self, self.meta, page=index, total=total)
            super().showPage()
        super().save()


def _canvas_factory(meta: DocumentMeta):
    """Return a ``canvasmaker`` that builds a :class:`_BrandedCanvas` bound to ``meta``."""

    def make(*args, **kwargs) -> _BrandedCanvas:
        """Construct the branded canvas and attach the document metadata."""
        pdf = _BrandedCanvas(*args, **kwargs)
        pdf.meta = meta
        return pdf

    return make


# --------------------------------------------------------------------------------------
# The one render entry point — every generator lays its story out through here.
# --------------------------------------------------------------------------------------


def build_pdf(story: list[Flowable], *, meta: DocumentMeta) -> bytes:
    """Lay a flowable ``story`` out as a themed A4 PDF and return its bytes (Issue #98).

    The single rendering path: it installs the branded header, footer and stamp via
    :class:`_BrandedCanvas` and leaves the flowable frame inside the page margins. Money
    documents pass a story containing :func:`money_table`; text documents typically go through
    :func:`render_lines_pdf`.

    Args:
        story: The document body as ReportLab flowables.
        meta: The header/footer/stamp context.

    Returns:
        The PDF file as bytes, ready to store verbatim.
    """
    buffer = BytesIO()
    document = SimpleDocTemplate(
        buffer,
        pagesize=_PAGE_SIZE,
        title=meta.title if not meta.reference else f"{meta.title} — {meta.reference}",
        topMargin=_MARGIN_TOP,
        bottomMargin=_MARGIN_BOTTOM,
        leftMargin=_MARGIN_X,
        rightMargin=_MARGIN_X,
        # ``invariant`` pins ReportLab's document id and creation timestamp, so the same
        # content and metadata render byte-identical output — the determinism the issue asks
        # for and that the golden-style tests pin.
        invariant=True,
    )
    document.build(story or [Spacer(1, 6)], canvasmaker=_canvas_factory(meta))
    return buffer.getvalue()


def lines_to_story(
    lines: list[str], style_map: dict[str, ParagraphStyle]
) -> list[Flowable]:
    """Turn a list of text ``lines`` into themed flowables (blank strings become vertical space).

    The bridge that lets the existing line-based generators adopt the theme unchanged: an ALL-CAPS
    line is rendered as a section heading, any other non-blank line as body text (HTML-escaped by
    :class:`~reportlab.platypus.Paragraph` callers), and a blank line as a small spacer.
    """
    from html import escape

    story: list[Flowable] = []
    for line in lines:
        stripped = line.strip()
        if not stripped:
            story.append(Spacer(1, 6))
            continue
        # A short, fully upper-case line is a section label in the existing bodies.
        is_heading = (
            stripped == stripped.upper()
            and len(stripped) <= 40
            and any(ch.isalpha() for ch in stripped)
        )
        style = style_map["heading"] if is_heading else style_map["body"]
        story.append(Paragraph(escape(line), style))
    return story


def render_lines_pdf(lines: list[str], *, meta: DocumentMeta) -> bytes:
    """Render a list of text ``lines`` as a themed A4 PDF and return its bytes (Issue #98).

    The drop-in replacement for each generator's former private ``_render_lines_pdf``: it converts
    the lines to themed flowables (:func:`lines_to_story`) and lays them out through
    :func:`build_pdf`, so a lease, inspection report, ledger, statement, report or certificate all
    gain the same branded header, footer and stamp with no per-document restyling.
    """
    return build_pdf(lines_to_story(lines, styles()), meta=meta)
