# ClinicQ – common Makefile (generated by bkreactor)

.PHONY: help run run-platform test test-fast test-unit test-postgres lint lint-fix hooks hooks-all check check-compose check-fast check-fix check-skip-pip-audit check-skip-trivy check-skip-pip-audit-trivy migrate-up migrate-down manifest-sync seed-rbac seed-rbac-check seed-rbac-dry-run gh-sync gh-sync-labels dev db-up db-down db-reset docker-up docker-down delete-example-module
help:
	@echo "ClinicQ – common targets"
	@echo "  make run [PORT=8000]            – run gateway on host (uvicorn)"
	@echo "  make run                        – run app locally (uvicorn with reload)"
	@echo "  make run-platform               – join local gateway (nginx :80 → :8002); PORT=5434 for Postgres"
	@echo "  make test                       – run every test (as make check and CI do)"
	@echo "  make test-fast                  – the inner loop: every test not marked slow"
	@echo "  make test-unit                  – the unit tests only (under 10 s)"
	@echo "  make test-postgres              – run the database-layer tests on the compose PostgreSQL (make db-up first)"
	@echo "  make lint                       – ruff check + ruff format --check (whole repo)"
	@echo "  make lint-fix                   – ruff check --fix + ruff format (in place)"
	@echo "  make hooks                      – install the pre-commit git hooks (once per clone)"
	@echo "  make hooks-all                  – run every pre-commit hook over all files"
	@echo "  make check                      – run full CI locally (quality, tests, Docker; pip-audit/Trivy warn-only)"
	@echo "  make check-compose              – check + Docker Compose smoke test (up → /health → down)"
	@echo "  make check-fast                 – quality + tests only (no Docker)"
	@echo "  make check-fix                  – fix ruff in place, then run full check"
	@echo "  make check-skip-pip-audit       – full check, skip pip-audit"
	@echo "  make check-skip-trivy           – full check, skip Trivy"
	@echo "  make check-skip-pip-audit-trivy – full check, skip pip-audit and Trivy"
	@echo "  make migrate-up                 – Apply Migrations"
	@echo "  make migrate-down               – Revert Migrations"
	@echo "  make seed-rbac                  – Seed/sync the whole RBAC catalog (run after migrate-up)"
	@echo "  make seed-rbac-check            – Fail if the DB has drifted from the shipped catalog"
	@echo "  make rbac-snapshot              – Regenerate the golden RBAC decision snapshot"
	@echo "  make rbac-snapshot-check        – Fail (with a diff) if any RBAC decision has moved"
	@echo "  make seed-rbac-dry-run          – Report what seed-rbac would change; write nothing"
	@echo "  make manifest-sync              – Deprecated alias for make seed-rbac"
	@echo "  make gh-sync                    – Sync milestones/issues to GitHub (DRY_RUN=1 to preview)"
	@echo "  make gh-sync-labels             – sync GitHub labels from docs/GITHUB/LABELS/labels.yml (ARGS='--dry-run')"
	@echo "  make delete-example-module      – remove the widgets example once you have your own"
	@echo "  make dev [PORT=8000]            – db-up, then run the API on the host with reload"
	@echo "  make db-up                      – start PostgreSQL 18/PostGIS + Redis, wait until healthy"
	@echo "  make db-down                    – stop the compose stack (data kept in volumes)"
	@echo "  make db-reset                   – wipe the database and Redis volumes, start fresh"
	@echo "  make docker-up                  – full stack in Docker: db, redis, API and nginx"
	@echo "  make docker-down                – stop the compose stack (data kept in volumes)"

PORT ?= 8000

run:
	uvicorn src.main:app --reload --host 127.0.0.1 --port $(PORT)

# Prerequisite: cd ../infra && ./scripts/run-local-platform.sh [--port PORT]
# Usage: make run-platform
#        make run-platform PORT=5434
#        make run-platform ARGS='--port 5434 --detach'
run-platform:
	./scripts/run-local-platform.sh $(if $(PORT),--port $(PORT),) $(ARGS)

test:
	pytest tests/ -v --no-cov -n auto --dist loadscope

# The selections CONTRIBUTING.md describes (Issue 7): markers are applied by location in
# tests/conftest.py, so these need nothing written on the tests themselves.
test-fast:
	pytest tests/ -q --no-cov -n auto --dist loadscope -m "not slow"

test-unit:
	pytest tests/ -q --no-cov -n auto --dist loadscope -m unit

# The database-layer tests (Issue 3): migrations, PostGIS and connection handling, each on a throwaway
# database created on the compose server and dropped afterwards. REQUIRE_POSTGRES_TESTS turns "no
# server" into a failure here, where `make test` would skip them.
DB_PORT ?= 5432
TEST_DATABASE_URL ?= postgresql://btk_user:change-me@localhost:$(DB_PORT)/btk
test-postgres:
	TEST_DATABASE_URL=$(TEST_DATABASE_URL) REQUIRE_POSTGRES_TESTS=1 pytest tests/ -m postgres -v --no-cov

# Bare ruff commands: the rule set lives in [tool.ruff] in pyproject.toml, shared
# with CI and the pre-commit hooks. `.` also covers alembic/ and scripts/.
lint:
	ruff check . && ruff format --check .

# Fix what ruff can fix, in place (same two commands the pre-commit hook runs)
lint-fix:
	ruff check . --fix && ruff format .

# Install the git hooks from .pre-commit-config.yaml (once per clone)
hooks:
	pre-commit install

# Run every pre-commit hook over the whole repo, not just staged files
hooks-all:
	pre-commit run --all-files

# Run same gates as CI: quality, tests, Docker build, Trivy (preserve quota by catching failures locally)
check:
	./scripts/ci-local.sh

# Same as check, plus Docker Compose smoke test (up → /health → down)
check-compose:
	./scripts/ci-local.sh --compose

# Quality + tests only (skip Docker build and Trivy)
check-fast:
	./scripts/ci-local.sh --no-docker

# Fix ruff issues in place, then run all checks
check-fix:
	./scripts/ci-local.sh --fix

# Full check, skip pip-audit (scans are warn-only by default; this skips the step entirely)
check-skip-pip-audit:
	./scripts/ci-local.sh --skip-pip-audit

# Full check, skip Trivy (scans are warn-only by default; this skips the step entirely)
check-skip-trivy:
	./scripts/ci-local.sh --skip-trivy

# Full check, skip both pip-audit and Trivy
check-skip-pip-audit-trivy:
	./scripts/ci-local.sh --skip-pip-audit --skip-trivy

# Apply Migrations
migrate-up:
	./scripts/db/alembic-upgrade.sh

# Apply Migrations Downgrade
migrate-down:
	./scripts/db/alembic-downgrade.sh

# Sync RBAC module manifests (src/modules/*/rbac_manifest.py) into the resources/actions/
# permissions/nav_gate_overrides catalog. Idempotent — safe on every deploy; run right after
# migrate-up (Issue #149). See docs/architecture/rbac-module-self-registration.md §4.
manifest-sync: seed-rbac  ## Deprecated alias — the sync is one step of `make seed-rbac` now.

# The single RBAC seed/sync entrypoint (Issue #169). Run after `make migrate-up`.
seed-rbac:
	python -m scripts.db.seed_rbac

# Same walk, no writes: non-zero exit plus a readable diff when the database is missing anything
# the manifests declare. This is what CI runs on every PR.
seed-rbac-check:
	python -m scripts.db.seed_rbac --check

seed-rbac-dry-run:
	python -m scripts.db.seed_rbac --dry-run

# Regenerate the golden RBAC decision snapshot (Issue #177, M29). A deliberate act, run by a
# person: CI re-derives and *diffs* this file but never rewrites it, because a guard that fixes
# itself is a rubber stamp. Run this when a change is meant to move a decision, and review the
# resulting diff in the same PR.
rbac-snapshot:
	python scripts/generate_rbac_snapshot.py

# The same walk, no writes: non-zero exit plus the list of moved decisions. Runs in CI through
# tests/integration/admin/test_rbac_decision_snapshot.py; this target is the local equivalent.
rbac-snapshot-check:
	python scripts/generate_rbac_snapshot.py --check

# Delete the worked example module once you have a module of your own. The script removes the
# package, its model and its templates, strips the lines that register it, and prints the one
# migration you still have to generate — dropping a table is not something a Makefile target
# should do behind your back.
delete-example-module:
	python scripts/delete_example_module.py

# Sync GitHub milestones + issues from docs/GITHUB specs. Idempotent; needs `gh` auth.
#   make gh-sync                    – create any missing milestones + issues
#   make gh-sync DRY_RUN=1          – preview only, no writes
#   make gh-sync GH_SYNC_ARGS=--validate    – local spec check, no gh calls
#   make gh-sync GH_SYNC_ARGS="--milestone M10"  – limit to one milestone folder
gh-sync:
	python3 scripts/gh_sync_issues.py $(if $(DRY_RUN),--dry-run,) $(GH_SYNC_ARGS)

# Local Docker stack (Issue 2). One compose project, `clinicq`: docker-compose.yml includes the
# db + redis definitions from docker-compose.db.yml, so every target drives the same containers
# and volumes. `--wait` returns once the health checks pass, and fails if they never do.
COMPOSE_DEV := docker compose -f infra/docker/docker-compose.yml --project-directory infra/docker

# Infra up, then the API on the host with reload
dev:
	./scripts/dev.sh --port $(PORT)

db-up:
	$(COMPOSE_DEV) up -d --wait db redis

db-down:
	$(COMPOSE_DEV) down

# Wipe and recreate: removes the containers and the pgdata/redisdata volumes (all local data),
# then starts db + redis from scratch. Follow with `make migrate-up`.
db-reset:
	$(COMPOSE_DEV) down -v --remove-orphans && $(COMPOSE_DEV) up -d --wait db redis

docker-up:
	$(COMPOSE_DEV) up -d --build --wait

docker-down:
	$(COMPOSE_DEV) down

# Upsert GitHub issue/PR labels from docs/GITHUB/LABELS/labels.yml (non-destructive).
# Preview:   make gh-sync-labels ARGS='--dry-run'
# Prune too: make gh-sync-labels ARGS='--prune'   (deletes labels not in the file)
gh-sync-labels:
	python scripts/gh_sync_labels.py $(ARGS)
