#!/usr/bin/env bash
#
# Build one environment's .env from its two halves, on the host, and never anywhere else.
#
#   deploy/env/<environment>.env   the settings that are not secret, committed and reviewed
# + the SOPS-encrypted secrets     decrypted here, in memory, with an age key that stays on the host
# = $DEPLOY_DIR/.env               mode 600, owned by the deploy user
#
# Usage:
#   scripts/cd/compose-env.sh <environment> <output>      # staging | production
#
# Environment:
#   SECRETS_FILE     the encrypted file (default: $SECRETS_DIR/clinicq/<environment>.env)
#   SECRETS_DIR      where Billykat7/infra is checked out on this host (default /etc/btk/secrets)
#   SOPS_AGE_KEY_FILE   the age identity (default $SECRETS_DIR/age.key). Preferred: it never
#                       leaves the host, so a repository compromise does not reach the secrets.
#   SOPS_AGE_KEY        the identity itself, for a CD run that carries it as an Environment
#                       secret instead. Written to a private temporary file for sops and removed.
#
# Why the secrets are not in this repository: it is public. Why they are not GitHub Environment
# secrets: those are write-only, unversioned, unauditable, and the whole file was pushing against
# the 48 KB-per-secret and 64 KB-per-repository limits. Encrypted in a private repository, a
# secret change is a reviewable commit, `git log` says when a value last moved, and the ciphertext
# is worthless without the age key.
#
# Nothing here prints a value. The only output is counts and setting names.

set -euo pipefail

HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
SECRETS_DIR="${SECRETS_DIR:-/etc/btk/secrets}"

environment="${1:-}"
output="${2:-}"

case "$environment" in
  staging | production) ;;
  *)
    echo "usage: $0 <staging|production> <output>" >&2
    exit 2
    ;;
esac
[[ -n "$output" ]] || {
  echo "usage: $0 <staging|production> <output>" >&2
  exit 2
}

config="$HERE/deploy/env/$environment.env"
secrets="${SECRETS_FILE:-$SECRETS_DIR/clinicq/$environment.env}"

[[ -f "$config" ]] || {
  echo "error: $config is missing" >&2
  exit 1
}
if [[ ! -f "$secrets" ]]; then
  echo "error: no secrets file for $environment." >&2
  echo "  Looked for: $secrets" >&2
  echo "  Check out Billykat7/infra to \$SECRETS_DIR, or set SECRETS_FILE." >&2
  echo "  docs/CICD/RUNBOOK_DEPLOY.md, 'Secrets'." >&2
  exit 1
fi

# The age identity. A key handed over in the environment is written to a file only sops can read,
# in a directory removed on the way out however this script ends.
scratch="$(mktemp -d)"
chmod 700 "$scratch"
trap 'rm -rf "$scratch"' EXIT

key_file="${SOPS_AGE_KEY_FILE:-$SECRETS_DIR/age.key}"
if [[ -n "${SOPS_AGE_KEY:-}" ]]; then
  key_file="$scratch/age.key"
  (umask 077 && printf '%s\n' "$SOPS_AGE_KEY" >"$key_file")
fi
[[ -r "$key_file" ]] || {
  echo "error: no age identity to decrypt $environment's secrets." >&2
  echo "  Looked for: $key_file (SOPS_AGE_KEY_FILE), and \$SOPS_AGE_KEY was empty." >&2
  exit 1
}

command -v sops >/dev/null || {
  echo "error: sops is not installed on this host (https://github.com/getsops/sops)." >&2
  exit 1
}

# Decrypt into the scratch directory rather than a pipe: sops failing mid-stream would otherwise
# leave a half-written .env that the app might still start with.
SOPS_AGE_KEY_FILE="$key_file" sops --decrypt --output "$scratch/secrets.env" "$secrets"

# Compose. The secrets go last, so a key in both files takes its secret value -- though
# tests/unit/platform/test_deploy_env.py makes that overlap impossible in the first place.
{
  echo "# Generated by scripts/cd/compose-env.sh for $environment at $(date -u +%FT%TZ)."
  echo "# Do not edit: the next deploy overwrites it. The non-secret half is deploy/env/$environment.env"
  echo "# in the clinicQ repository; the secret half is clinicq/$environment.env in Billykat7/infra."
  echo
  cat "$config"
  echo
  echo "# ── secrets ───────────────────────────────────────────────────────────────────────────"
  cat "$scratch/secrets.env"
} >"$scratch/composed.env"

# Only now replace the live file, and only as a whole.
(umask 077 && cp "$scratch/composed.env" "$output")
chmod 600 "$output"

config_keys="$(grep -cE '^[A-Za-z_][A-Za-z0-9_]*=' "$config" || true)"
secret_keys="$(grep -cE '^[A-Za-z_][A-Za-z0-9_]*=' "$scratch/secrets.env" || true)"
echo "Settings: $config_keys from deploy/env/$environment.env (in git) + $secret_keys decrypted = $(grep -cE '^[A-Za-z_][A-Za-z0-9_]*=' "$output") keys."
