#!/usr/bin/env bash
# shellcheck disable=SC2016
#
# LEGACY / emergency helper only.
# Production CD must use the gateway copy:
#   /opt/btk/gateway/scripts/cd/write-prod-env.sh
# via Billykat7/infra cd-product.yml.
#
# To run this copy (local emergency / offline host):
#   BTK_ALLOW_LEGACY_WRITE_PROD_ENV=1 ./scripts/cd/write-prod-env.sh
#
# Writes `.env` as KEY=value lines (empty values stripped). Export IMAGE before
# running so docker-compose.prod.yml can interpolate ${IMAGE}.
#
# Platform identity defaults: PROJECT_SLUG=clinicq, APP_PORT=8011,
# DB_SCHEMA=clinicq, DOMAIN=clinicq.bkatalayi.com, TRUST_PROXY_HEADERS=true.
set -e

if [[ "${BTK_ALLOW_LEGACY_WRITE_PROD_ENV:-}" != "1" ]]; then
  echo "error: clinicq scripts/cd/write-prod-env.sh is legacy." >&2
  echo "  Production CD uses: /opt/btk/gateway/scripts/cd/write-prod-env.sh" >&2
  echo "  Override for emergency use: BTK_ALLOW_LEGACY_WRITE_PROD_ENV=1 $0 $*" >&2
  exit 1
fi

OUT="${1:-.env}"
_DEFAULT_DOMAIN="clinicq.bkatalayi.com"
_DEFAULT_ACME_EMAIL="deployer@bkatalayi.com"
_DEFAULT_APP_PORT="8011"
_DEFAULT_PROJECT_SLUG="clinicq"
_DEFAULT_DB_SCHEMA="clinicq"

_normalize_domain() {
  local d="${1:-}"
  d="${d#"${d%%[![:space:]]*}"}"
  d="${d%"${d##*[![:space:]]}"}"
  [[ -z "$d" ]] && return 0
  d="$(printf '%s' "$d" | sed -E 's|^[Hh][Tt][Tt][Pp][Ss]?://||')"
  d="${d%%/*}"
  d="${d%%:*}"
  d="${d%.}"
  printf '%s' "$d"
}

DOMAIN="$(_normalize_domain "${DOMAIN:-}")"
DOMAIN="${DOMAIN:-$_DEFAULT_DOMAIN}"
ACME_EMAIL="${ACME_EMAIL:-$_DEFAULT_ACME_EMAIL}"
APP_PORT="${APP_PORT:-$_DEFAULT_APP_PORT}"
PROJECT_SLUG="${PROJECT_SLUG:-$_DEFAULT_PROJECT_SLUG}"
DB_SCHEMA="${DB_SCHEMA:-$_DEFAULT_DB_SCHEMA}"
TRUST_PROXY_HEADERS="${TRUST_PROXY_HEADERS:-true}"
ENVIRONMENT="${ENVIRONMENT:-production}"
if [[ -z "${CORS_ORIGINS:-}" ]]; then
  CORS_ORIGINS="https://${DOMAIN}"
fi

cat >"$OUT" <<EOF
ACCESS_TOKEN_EXPIRE_MINUTES=${ACCESS_TOKEN_EXPIRE_MINUTES}
ACME_EMAIL=${ACME_EMAIL}
ACTIVATION_LINK_EXPIRE_HOURS=${ACTIVATION_LINK_EXPIRE_HOURS}
ALGORITHM=${ALGORITHM}
API_URL=${API_URL}
APP_NAME=${APP_NAME}
APP_PORT=${APP_PORT}
APP_VERSION=${APP_VERSION}
AUTH_ENABLED=${AUTH_ENABLED}
AUTH_HTTP_RL_OAUTH_START_PER_MINUTE=${AUTH_HTTP_RL_OAUTH_START_PER_MINUTE}
AUTH_HTTP_RL_OTP_REQUEST_PER_MINUTE=${AUTH_HTTP_RL_OTP_REQUEST_PER_MINUTE}
AUTH_HTTP_RL_OTP_VERIFY_PER_MINUTE=${AUTH_HTTP_RL_OTP_VERIFY_PER_MINUTE}
AUTH_HTTP_RL_REFRESH_PER_MINUTE=${AUTH_HTTP_RL_REFRESH_PER_MINUTE}
AUTH_HTTP_RL_RESEND_VERIFICATION_PER_MINUTE=${AUTH_HTTP_RL_RESEND_VERIFICATION_PER_MINUTE}
AUTH_HTTP_RL_FLIGHT_ALERTS_CREATE_PER_MINUTE=${AUTH_HTTP_RL_FLIGHT_ALERTS_CREATE_PER_MINUTE}
AUTH_HTTP_RL_SIGNUP_PER_MINUTE=${AUTH_HTTP_RL_SIGNUP_PER_MINUTE}
AUTH_OTP_LOGIN_ENABLED=${AUTH_OTP_LOGIN_ENABLED:-true}
AUTH_PASSWORD_LOGIN_ENABLED=${AUTH_PASSWORD_LOGIN_ENABLED:-false}
AUTH_TYPE=${AUTH_TYPE}
AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
AWS_REGION_CCTV=${AWS_REGION_CCTV}
AWS_REGION_DOCS=${AWS_REGION_DOCS}
AWS_S3_BASE_URL=${AWS_S3_BASE_URL}
AWS_S3_BUCKET=${AWS_S3_BUCKET}
AWS_S3_BUCKET_CCTV=${AWS_S3_BUCKET_CCTV}
AWS_S3_BUCKET_DOCS=${AWS_S3_BUCKET_DOCS}
AWS_S3_CCTV_CREATE_BUCKET_IF_MISSING=${AWS_S3_CCTV_CREATE_BUCKET_IF_MISSING}
AWS_S3_DEFAULT_SITE_CCTV=${AWS_S3_DEFAULT_SITE_CCTV}
AWS_S3_LOGGING_ENABLED=${AWS_S3_LOGGING_ENABLED}
AWS_S3_REGION=${AWS_S3_REGION}
AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
AWS_SSL_CERT_ENABLED=${AWS_SSL_CERT_ENABLED}
CONTACT_SUPPORT_EMAIL=${CONTACT_SUPPORT_EMAIL}
COMMIT_SHA=${COMMIT_SHA}
CORS_ORIGINS=${CORS_ORIGINS}
DATABASE_URL=${DATABASE_URL}
DB_HOST=${DB_HOST}
DB_NAME=${DB_NAME}
DB_OPTS=${DB_OPTS}
DB_PASSWORD=${DB_PASSWORD}
DB_SCHEMA=${DB_SCHEMA}
DB_USER=${DB_USER}
DEBUG=${DEBUG}
DEFAULT_USER_PASSWORD=${DEFAULT_USER_PASSWORD}
DOMAIN=${DOMAIN}
ENVIRONMENT=${ENVIRONMENT}
FAST_FLIGHTS_ENABLED=${FAST_FLIGHTS_ENABLED}
FAST_FLIGHTS_TIMEOUT_S=${FAST_FLIGHTS_TIMEOUT_S}
FFMPEG_PATH=${FFMPEG_PATH}
FLIGHT_ALERT_COOLDOWN_HOURS=${FLIGHT_ALERT_COOLDOWN_HOURS}
FLIGHT_ALERT_EMAIL_DISPATCH_MAX_ATTEMPTS=${FLIGHT_ALERT_EMAIL_DISPATCH_MAX_ATTEMPTS}
FLIGHT_ALERT_FROM_EMAIL=${FLIGHT_ALERT_FROM_EMAIL}
FLIGHT_ALERT_SMTP_USER=${FLIGHT_ALERT_SMTP_USER}
FLIGHT_ALERTS_MANAGE_PATH=${FLIGHT_ALERTS_MANAGE_PATH}
FLIGHT_INGEST_DAILY_BUDGET=${FLIGHT_INGEST_DAILY_BUDGET}
FLIGHT_INGEST_OFFSETS=${FLIGHT_INGEST_OFFSETS}
FLIGHT_MAX_ACTIVE_SUBS_PER_USER=${FLIGHT_MAX_ACTIVE_SUBS_PER_USER}
FLIGHT_MODEL_CACHE_DIR=${FLIGHT_MODEL_CACHE_DIR}
FLIGHT_MODEL_PROMOTE_MARGIN=${FLIGHT_MODEL_PROMOTE_MARGIN}
FLIGHT_MODEL_S3_BUCKET=${FLIGHT_MODEL_S3_BUCKET}
FLIGHT_MODEL_S3_PREFIX=${FLIGHT_MODEL_S3_PREFIX}
FLIGHT_RECO_WEIGHTS=${FLIGHT_RECO_WEIGHTS}
FLIGHT_SCHEDULER_ENABLED=${FLIGHT_SCHEDULER_ENABLED}
FRONTEND_URL=${FRONTEND_URL}
GATEWAY_COMPOSE_DIR=${GATEWAY_COMPOSE_DIR:-/opt/btk/gateway}
GIT_SHA=${GIT_SHA}
HOST=${HOST}
IMAGE=${IMAGE}
IPGEOLOCATION_API_KEY_1=${IPGEOLOCATION_API_KEY_1}
IPGEOLOCATION_API_KEY_2=${IPGEOLOCATION_API_KEY_2}
IPGEOLOCATION_API_KEY_3=${IPGEOLOCATION_API_KEY_3}
IPGEOLOCATION_API_KEY_4=${IPGEOLOCATION_API_KEY_4}
IPGEOLOCATION_API_KEY_5=${IPGEOLOCATION_API_KEY_5}
IPGEOLOCATION_BASE_URL=${IPGEOLOCATION_BASE_URL}
IPGEOLOCATION_CACHE_TTL_SECONDS=${IPGEOLOCATION_CACHE_TTL_SECONDS}
IPGEOLOCATION_INCLUDE_GEO_ACCURACY=${IPGEOLOCATION_INCLUDE_GEO_ACCURACY}
IPGEOLOCATION_TIMEOUT_S=${IPGEOLOCATION_TIMEOUT_S}
JWT_ACCESS_EXPIRE_MINUTES=${JWT_ACCESS_EXPIRE_MINUTES}
JWT_SECRET=${JWT_SECRET}
LB_READY_DELAY=${LB_READY_DELAY}
LB_READY_RETRIES=${LB_READY_RETRIES}
LOG_FORMAT=${LOG_FORMAT}
LOG_LEVEL=${LOG_LEVEL}
MAPS_COMPOSE_DIR=${MAPS_COMPOSE_DIR:-.}
MAX_READY_RETRIES=${MAX_READY_RETRIES}
METRICS_ENABLED=${METRICS_ENABLED}
MFA_BACKUP_CODE_COUNT=${MFA_BACKUP_CODE_COUNT}
MFA_BACKUP_CODE_LENGTH=${MFA_BACKUP_CODE_LENGTH}
MFA_ENABLED=${MFA_ENABLED}
OAUTH_AMAZON_AUTH_URL=${OAUTH_AMAZON_AUTH_URL}
OAUTH_AMAZON_CLIENT_ID=${OAUTH_AMAZON_CLIENT_ID}
OAUTH_AMAZON_CLIENT_SECRET=${OAUTH_AMAZON_CLIENT_SECRET}
OAUTH_AMAZON_ENABLED=${OAUTH_AMAZON_ENABLED:-False}
OAUTH_AMAZON_SCOPES=${OAUTH_AMAZON_SCOPES}
OAUTH_AMAZON_TOKEN_URL=${OAUTH_AMAZON_TOKEN_URL}
OAUTH_AMAZON_USER_URL=${OAUTH_AMAZON_USER_URL}
OAUTH_APPLE_AUTH_URL=${OAUTH_APPLE_AUTH_URL}
OAUTH_APPLE_CLIENT_ID=${OAUTH_APPLE_CLIENT_ID}
OAUTH_APPLE_ENABLED=${OAUTH_APPLE_ENABLED:-True}
OAUTH_APPLE_KEY_ID=${OAUTH_APPLE_KEY_ID}
OAUTH_APPLE_SCOPES=${OAUTH_APPLE_SCOPES}
OAUTH_APPLE_SERVICE_ID=${OAUTH_APPLE_SERVICE_ID}
OAUTH_APPLE_TEAM_ID=${OAUTH_APPLE_TEAM_ID}
OAUTH_APPLE_TOKEN_URL=${OAUTH_APPLE_TOKEN_URL}
OAUTH_DISCORD_AUTH_URL=${OAUTH_DISCORD_AUTH_URL}
OAUTH_DISCORD_CLIENT_ID=${OAUTH_DISCORD_CLIENT_ID}
OAUTH_DISCORD_CLIENT_SECRET=${OAUTH_DISCORD_CLIENT_SECRET}
OAUTH_DISCORD_ENABLED=${OAUTH_DISCORD_ENABLED:-False}
OAUTH_DISCORD_SCOPES=${OAUTH_DISCORD_SCOPES}
OAUTH_DISCORD_TOKEN_URL=${OAUTH_DISCORD_TOKEN_URL}
OAUTH_DISCORD_USER_URL=${OAUTH_DISCORD_USER_URL}
OAUTH_FACEBOOK_APP_ID=${OAUTH_FACEBOOK_APP_ID}
OAUTH_FACEBOOK_APP_SECRET=${OAUTH_FACEBOOK_APP_SECRET}
OAUTH_FACEBOOK_AUTH_URL=${OAUTH_FACEBOOK_AUTH_URL}
OAUTH_FACEBOOK_ENABLED=${OAUTH_FACEBOOK_ENABLED:-False}
OAUTH_FACEBOOK_ME_URL=${OAUTH_FACEBOOK_ME_URL}
OAUTH_FACEBOOK_SCOPES=${OAUTH_FACEBOOK_SCOPES}
OAUTH_FACEBOOK_TOKEN_URL=${OAUTH_FACEBOOK_TOKEN_URL}
OAUTH_GITHUB_AUTH_URL=${OAUTH_GITHUB_AUTH_URL}
OAUTH_GITHUB_CLIENT_ID=${OAUTH_GITHUB_CLIENT_ID}
OAUTH_GITHUB_CLIENT_SECRET=${OAUTH_GITHUB_CLIENT_SECRET}
OAUTH_GITHUB_EMAILS_URL=${OAUTH_GITHUB_EMAILS_URL}
OAUTH_GITHUB_ENABLED=${OAUTH_GITHUB_ENABLED:-False}
OAUTH_GITHUB_SCOPES=${OAUTH_GITHUB_SCOPES}
OAUTH_GITHUB_TOKEN_URL=${OAUTH_GITHUB_TOKEN_URL}
OAUTH_GITHUB_USER_URL=${OAUTH_GITHUB_USER_URL}
OAUTH_GITLAB_AUTH_URL=${OAUTH_GITLAB_AUTH_URL}
OAUTH_GITLAB_CLIENT_ID=${OAUTH_GITLAB_CLIENT_ID}
OAUTH_GITLAB_CLIENT_SECRET=${OAUTH_GITLAB_CLIENT_SECRET}
OAUTH_GITLAB_ENABLED=${OAUTH_GITLAB_ENABLED:-False}
OAUTH_GITLAB_SCOPES=${OAUTH_GITLAB_SCOPES}
OAUTH_GITLAB_TOKEN_URL=${OAUTH_GITLAB_TOKEN_URL}
OAUTH_GITLAB_USER_URL=${OAUTH_GITLAB_USER_URL}
OAUTH_GOOGLE_AUTH_URL=${OAUTH_GOOGLE_AUTH_URL}
OAUTH_GOOGLE_CLIENT_ID=${OAUTH_GOOGLE_CLIENT_ID}
OAUTH_GOOGLE_CLIENT_SECRET=${OAUTH_GOOGLE_CLIENT_SECRET}
OAUTH_GOOGLE_ENABLED=${OAUTH_GOOGLE_ENABLED:-True}
OAUTH_GOOGLE_SCOPES=${OAUTH_GOOGLE_SCOPES}
OAUTH_GOOGLE_TOKEN_URL=${OAUTH_GOOGLE_TOKEN_URL}
OAUTH_GOOGLE_USERINFO_URL=${OAUTH_GOOGLE_USERINFO_URL}
OAUTH_LINKEDIN_AUTH_URL=${OAUTH_LINKEDIN_AUTH_URL}
OAUTH_LINKEDIN_CLIENT_ID=${OAUTH_LINKEDIN_CLIENT_ID}
OAUTH_LINKEDIN_CLIENT_SECRET=${OAUTH_LINKEDIN_CLIENT_SECRET}
OAUTH_LINKEDIN_ENABLED=${OAUTH_LINKEDIN_ENABLED:-True}
OAUTH_LINKEDIN_SCOPES=${OAUTH_LINKEDIN_SCOPES}
OAUTH_LINKEDIN_TOKEN_URL=${OAUTH_LINKEDIN_TOKEN_URL}
OAUTH_LINKEDIN_USERINFO_URL=${OAUTH_LINKEDIN_USERINFO_URL}
OAUTH_MICROSOFT_BASE_URL=${OAUTH_MICROSOFT_BASE_URL}
OAUTH_MICROSOFT_CLIENT_ID=${OAUTH_MICROSOFT_CLIENT_ID}
OAUTH_MICROSOFT_CLIENT_SECRET=${OAUTH_MICROSOFT_CLIENT_SECRET}
OAUTH_MICROSOFT_ENABLED=${OAUTH_MICROSOFT_ENABLED:-True}
OAUTH_MICROSOFT_SCOPES=${OAUTH_MICROSOFT_SCOPES}
OAUTH_MICROSOFT_TENANT=${OAUTH_MICROSOFT_TENANT}
OAUTH_MICROSOFT_USERINFO_URL=${OAUTH_MICROSOFT_USERINFO_URL}
OAUTH_SLACK_AUTH_URL=${OAUTH_SLACK_AUTH_URL}
OAUTH_SLACK_CLIENT_ID=${OAUTH_SLACK_CLIENT_ID}
OAUTH_SLACK_CLIENT_SECRET=${OAUTH_SLACK_CLIENT_SECRET}
OAUTH_SLACK_ENABLED=${OAUTH_SLACK_ENABLED:-False}
OAUTH_SLACK_IDENTITY_URL=${OAUTH_SLACK_IDENTITY_URL}
OAUTH_SLACK_SCOPES=${OAUTH_SLACK_SCOPES}
OAUTH_SLACK_TOKEN_URL=${OAUTH_SLACK_TOKEN_URL}
OAUTH_SPOTIFY_AUTH_URL=${OAUTH_SPOTIFY_AUTH_URL}
OAUTH_SPOTIFY_CLIENT_ID=${OAUTH_SPOTIFY_CLIENT_ID}
OAUTH_SPOTIFY_CLIENT_SECRET=${OAUTH_SPOTIFY_CLIENT_SECRET}
OAUTH_SPOTIFY_ENABLED=${OAUTH_SPOTIFY_ENABLED:-False}
OAUTH_SPOTIFY_SCOPES=${OAUTH_SPOTIFY_SCOPES}
OAUTH_SPOTIFY_TOKEN_URL=${OAUTH_SPOTIFY_TOKEN_URL}
OAUTH_SPOTIFY_USER_URL=${OAUTH_SPOTIFY_USER_URL}
OAUTH_X_AUTH_URL=${OAUTH_X_AUTH_URL}
OAUTH_X_CLIENT_ID=${OAUTH_X_CLIENT_ID}
OAUTH_X_CLIENT_SECRET=${OAUTH_X_CLIENT_SECRET}
OAUTH_X_ENABLED=${OAUTH_X_ENABLED:-False}
OAUTH_X_SCOPES=${OAUTH_X_SCOPES}
OAUTH_X_TOKEN_URL=${OAUTH_X_TOKEN_URL}
OAUTH_X_USER_URL=${OAUTH_X_USER_URL}
OAUTH_YAHOO_AUTH_URL=${OAUTH_YAHOO_AUTH_URL}
OAUTH_YAHOO_CLIENT_ID=${OAUTH_YAHOO_CLIENT_ID}
OAUTH_YAHOO_CLIENT_SECRET=${OAUTH_YAHOO_CLIENT_SECRET}
OAUTH_YAHOO_ENABLED=${OAUTH_YAHOO_ENABLED:-False}
OAUTH_YAHOO_SCOPES=${OAUTH_YAHOO_SCOPES}
OAUTH_YAHOO_TOKEN_URL=${OAUTH_YAHOO_TOKEN_URL}
OAUTH_YAHOO_USERINFO_URL=${OAUTH_YAHOO_USERINFO_URL}
PORT=${PORT}
PRODUCTION_URL=${PRODUCTION_URL}
PROJECT_SLUG=${PROJECT_SLUG}
REDIS_PASSWORD=${REDIS_PASSWORD}
REDIS_PORT=${REDIS_PORT}
REDIS_URL=${REDIS_URL}
REFRESH_TOKEN_COOKIE_NAME=${REFRESH_TOKEN_COOKIE_NAME}
REFRESH_TOKEN_EXPIRE_DAYS=${REFRESH_TOKEN_EXPIRE_DAYS}
SECRET_KEY=${SECRET_KEY}
SESSION_INACTIVITY_TIMEOUT_MINUTES=${SESSION_INACTIVITY_TIMEOUT_MINUTES}
SESSION_INACTIVITY_WARNING_MINUTES=${SESSION_INACTIVITY_WARNING_MINUTES}
SERPAPI_KEY_1=${SERPAPI_KEY_1}
SERPAPI_KEY_2=${SERPAPI_KEY_2}
SERPAPI_KEY_3=${SERPAPI_KEY_3}
SERPAPI_KEY_4=${SERPAPI_KEY_4}
SERPAPI_KEY_5=${SERPAPI_KEY_5}
SERPAPI_MONTHLY_CAP=${SERPAPI_MONTHLY_CAP}
SERPAPI_TIMEOUT_S=${SERPAPI_TIMEOUT_S}
SIGNUP_ENABLED=${SIGNUP_ENABLED:-false}
SMTP_FROM_EMAIL=${SMTP_FROM_EMAIL}
SMTP_HOST=${SMTP_HOST}
SMTP_PORT=${SMTP_PORT}
SMTP_SUPPORT_FROM_EMAIL=${SMTP_SUPPORT_FROM_EMAIL}
SMTP_SUPPORT_USER=${SMTP_SUPPORT_USER}
SMTP_TLS=${SMTP_TLS}
SMTP_USER=${SMTP_USER}
STRIPE_API_KEY=${STRIPE_API_KEY}
STRIPE_PUBLISHABLE_KEY=${STRIPE_PUBLISHABLE_KEY}
STRIPE_WEBHOOK_SECRET=${STRIPE_WEBHOOK_SECRET}
TRUST_PROXY_HEADERS=${TRUST_PROXY_HEADERS}
TWILIO_ACCOUNT_SID=${TWILIO_ACCOUNT_SID}
TWILIO_AUTH_TOKEN=${TWILIO_AUTH_TOKEN}
TWILIO_PHONE_NUMBER=${TWILIO_PHONE_NUMBER}
VIDEO_DEFAULT_QUALITIES=${VIDEO_DEFAULT_QUALITIES}
VIDEO_HLS_PRESIGNED_EXPIRES=${VIDEO_HLS_PRESIGNED_EXPIRES}
VIDEO_MAX_SIZE_GB=${VIDEO_MAX_SIZE_GB}
WORKERS=${WORKERS}

EOF

# Drop KEY= with no value — empty env vars break Pydantic (int/bool parsing) vs omitting the key.
grep -Ev '^[A-Za-z_][A-Za-z0-9_]*=$' "$OUT" >"${OUT}.tmp" && mv "${OUT}.tmp" "$OUT"

# Append KEY=value with value JSON-encoded (safe for $, ", newlines in secrets).
_append_json_env_line() {
  local key="$1"
  local val="${2:-}"
  if [ -z "$val" ]; then
    return 0
  fi
  if ! command -v python3 >/dev/null 2>&1; then
    echo "::error::python3 is required to append ${key} (JSON-quoted .env line)." >&2
    exit 1
  fi
  printf '%s' "$val" | python3 -c 'import sys, json; k = sys.argv[1]; v = sys.stdin.read(); print(f"{k}={json.dumps(v)}")' "$key" >>"$OUT"
}

_append_json_env_line "SMTP_PASSWORD" "${SMTP_PASSWORD:-}"
_append_json_env_line "SMTP_SUPPORT_PASSWORD" "${SMTP_SUPPORT_PASSWORD:-}"
_append_json_env_line "FLIGHT_ALERT_SMTP_PASSWORD" "${FLIGHT_ALERT_SMTP_PASSWORD:-}"

if [ -n "${OAUTH_APPLE_PRIVATE_KEY:-}" ]; then
  if ! command -v python3 >/dev/null 2>&1; then
    echo "::error::python3 is required to append OAUTH_APPLE_PRIVATE_KEY (multiline PEM)." >&2
    exit 1
  fi
  printf '%s' "$OAUTH_APPLE_PRIVATE_KEY" | python3 -c 'import sys,json; k="OAUTH_APPLE_PRIVATE_KEY"; v=sys.stdin.read(); print(f"{k}={json.dumps(v)}")' >>"$OUT"
fi
